### PR TITLE
fix: make it compatible with node's --disable-proto=throw

### LINKED ISSUE #79: fast-copy not compatible with NodeJS's --disable-proto=throw option
When running NodeJS with `--disable-proto` option, fast-copy fails due to an access to the `__proto__` property. Many people need/want to avoid this kind of access because it facilitates "prototype pollution" attacks.

- https://learn.snyk.io/lessons/prototype-pollution/javascript/

### PR DESCRIPTION
**Pull request by castarco**
Many people use the option [`--disable-proto=delete`/`--disable-proto=throw`](https://nodejs.org/api/cli.html#--disable-protomode) in NodeJS to minimise the probability of prototype pollution attacks. Because of that, `__proto__` might not be available (or throw an error if accessed).

- Fixes #79

### CODE REVIEW

**Comment by planttheidea** [comment]
This is a good change. In previous V8 versions, the performance cost was substantial, so `__proto__` was preferred, but testing locally it seems the difference is minimal now. I have some styling feedback, but that's all.

File: src/index.ts [hunk 1]
```diff
@@ -24,6 +24,8 @@ export type { State } from './copier';
 const { isArray } = Array;
 const { assign, getPrototypeOf } = Object;
 
+const _getPrototypeOf = getPrototypeOf || (obj) => obj.__proto__
```
Comment (planttheidea) [inline src/index.ts:27]: Both for smaller footprint, but also to avoid the leading `_` prefix bailing out ESLint, can you update to instead do property access and avoid the local ref above?

```ts
const { assign } = Object;

const getPrototypeOf = Object.getPrototypeOf || (object) => object.__proto__;
```

**Review by planttheidea — CHANGES_REQUESTED** [review]

**Comment by planttheidea** [comment]
Not sure if this is possible considering it is so low-level, but is there a way we can add a test for this?

File: src/index.ts (hunk 1 above)
Comment (castarco) [reply src/index.ts:27]: Will do, sorry, I didn't see the GH notification until today.

Comment (castarco) [reply src/index.ts]: Done. I kept the `obj` variable name for the lambda function, to minimize confusion with `Object`.

**Comment by castarco** [comment]
> Not sure if this is possible considering it is so low-level, but is there a way we can add a test for this?

I'm not sure either. It's probably possible, what I don't know is how clean/maintainable that test would be (as it requires running Node with a different set of options, so we need to spawn an independent process for it).

**Comment by castarco** [comment]
Hi @planttheidea , after checking carefully, I've concluded that I was overly optimistic about being able to test that. The way I define `getPrototypeOf` (being global at the module level) makes it difficult to do it.

- I could mock it from outside, but that would render the test almost useless, as we have no way to ensure that the mocked value corresponds to what out code would produce (I know it's a trivial condition, but we might have changes in code later).
- I could try to set `Object.getPrototypeOf` to `undefined`, but I have to do it before loading the module into the test, and I cannot "revert" it to test the other branch where `Object.getPrototypeOf` is defined (because the value gets cached at the module level).

**Review by planttheidea — APPROVED** [review]
