### PR TITLE
safety around constructing with object constructor

### LINKED ISSUE #19: One error: Digest method not supported
```javascript
const _ = require('lodash');
const Copy = require('fast-copy');

const hash = Crypto.createHash('sha256');
hash.update(sendPacketData);
//let newHash = _.cloneDeep(hash);      //success
let newHash = Copy(hash, {isStrict: true});  //failed
newHash.update(item.data);
```
    at getObjectCloneStrict (d:\src\node_modules\fast-copy\dist\fast-copy.cjs.js:114:36)
    at handleCopy (d:\src\node_modules\fast-copy\dist\fast-copy.cjs.js:286:16)
    at copy (d:\src\node_modules\fast-copy\dist\fast-copy.cjs.js:288:12)
    at d:\src\node\WechatWrap\test\testPacketDecrypt.js:59:23
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (d:\src\node\WechatWrap\test\testPacketDecrypt.js:54:9)
    at Module._compile (internal/modules/cjs/loader.js:686:14)
Waiting for the debugger to disconnect...
Error: Digest method not supported
utils.ts:70
    at getCleanClone (d:\src\node_modules\fast-copy\dist\fast-copy.cjs.js:56:16)
    at getObjectCloneStrict (d:\src\node_modules\fast-copy\dist\fast-copy.cjs.js:105:17)
    at handleCopy (d:\src\node_modules\fast-copy\dist\fast-copy.cjs.js:286:16)
    at getObjectCloneStrict (d:\src\node_modules\fast-copy\dist\fast-copy.cjs.js:114:36)
    at handleCopy (d:\src\node_modules\fast-copy\dist\fast-copy.cjs.js:286:16)
    at copy (d:\src\node_modules\fast-copy\dist\fast-copy.cjs.js:288:12)
    at d:\src\node\WechatWrap\test\testPacketDecrypt.js:59:23
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (d:\src\node\WechatWrap\test\testPacketDecrypt.js:54:9)
    at Module._compile (internal/modules/cjs/loader.js:686:14)

### PR DESCRIPTION
**Pull request by planttheidea**
Trying to clone a `hash` generated by the node `crypto` package throws an error, whereas in `lodash` it handles it just fine. It appears that is because lodash uses `toString`-based tags to determine what clone to produce, which means a standard POJO is being created. Wrapping the `new object.constructor()` in a `try` prevents the error from occurring and allows the fallback of using `Object.create` to create the clone.

Should fix #19

### CODE REVIEW

File: src/utils.ts [hunk 1]
```diff
@@ -67,7 +67,9 @@ export const getCleanClone = (object: any, realm: FastCopy.Realm): any => {
   }
 
   if (~toStringFunction.call(object.constructor).indexOf('[native code]')) {
-    return new object.constructor();
+    try {
+      return new object.constructor();
```
Comment (planttheidea) [inline src/utils.ts]: this is the real change, wrapping things in a `try` to allow graceful fallback to creating the object via `Object.create()`
